import { existsSync } from "node:fs";
import { copyFile, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { codexHomeDir, resolveInstallPaths, type InstallScope } from "../utils/paths.js";
import { readTextFileIfExists, writeTextFile, type WriteStatus } from "../utils/fs.js";

export const MANAGED_MARKER = "<!-- AGMO:GENERATED:AGENTS-MD -->";
export const GENERATED_START = "<!-- AGMO:GENERATED:START -->";
export const GENERATED_END = "<!-- AGMO:GENERATED:END -->";
export const RUNTIME_START = "<!-- AGMO:RUNTIME:START -->";
export const RUNTIME_END = "<!-- AGMO:RUNTIME:END -->";
export const TEAM_WORKER_START = "<!-- AGMO:TEAM:WORKER:START -->";
export const TEAM_WORKER_END = "<!-- AGMO:TEAM:WORKER:END -->";
export const MANUAL_START = "<!-- AGMO:MANUAL:START -->";
export const MANUAL_END = "<!-- AGMO:MANUAL:END -->";

const LEGACY_GENERATED_SENTINEL = "This file is generated by `agmo setup`.";
const ACTIVE_SESSION_WINDOW_MS = 24 * 60 * 60 * 1000;

export type AgentsMdWriteStatus = WriteStatus | "skipped";

export type AgentsMdInspection = {
  exists: boolean;
  managed: boolean;
  legacy_generated: boolean;
  generated_section_present: boolean;
  runtime_section_present: boolean;
  team_worker_section_present: boolean;
  manual_section_present: boolean;
};

export type SyncAgentsMdResult = {
  path: string;
  status: AgentsMdWriteStatus;
  reason?: string;
  forced?: boolean;
  backup?: {
    created: boolean;
    path?: string;
  };
  guard?: {
    skipped_for_unmanaged?: boolean;
    skipped_for_active_session?: boolean;
    active_sessions_detected?: string[];
  };
  existing_file: AgentsMdInspection;
  next_file: {
    managed: true;
    runtime_section_present: boolean;
    team_worker_section_present: boolean;
    manual_section_present: boolean;
  };
};

type SessionStateLike = {
  session_id?: unknown;
  active?: unknown;
  updated_at?: unknown;
};

function extractSection(
  content: string,
  startMarker: string,
  endMarker: string
): string | null {
  const start = content.indexOf(startMarker);
  const end = content.indexOf(endMarker);

  if (start === -1 || end === -1 || end < start) {
    return null;
  }

  return content.slice(start + startMarker.length, end).trim();
}

function isManagedAgentsFile(content: string): boolean {
  return content.includes(MANAGED_MARKER);
}

function isLegacyGeneratedAgentsFile(content: string): boolean {
  if (isManagedAgentsFile(content)) {
    return false;
  }

  return (
    content.includes(LEGACY_GENERATED_SENTINEL) &&
    content.includes("# Agmo Runtime Instructions")
  );
}

export function inspectAgentsContent(content: string | null): AgentsMdInspection {
  if (!content) {
    return {
      exists: false,
      managed: false,
      legacy_generated: false,
      generated_section_present: false,
      runtime_section_present: false,
      team_worker_section_present: false,
      manual_section_present: false
    };
  }

  return {
    exists: true,
    managed: isManagedAgentsFile(content),
    legacy_generated: isLegacyGeneratedAgentsFile(content),
    generated_section_present: extractSection(content, GENERATED_START, GENERATED_END) !== null,
    runtime_section_present: extractSection(content, RUNTIME_START, RUNTIME_END) !== null,
    team_worker_section_present:
      extractSection(content, TEAM_WORKER_START, TEAM_WORKER_END) !== null,
    manual_section_present: extractSection(content, MANUAL_START, MANUAL_END) !== null
  };
}

function defaultManualBody(scope: InstallScope): string {
  const scopeNotes =
    scope === "project"
      ? [
          "- Add repo-specific coding conventions, verification commands, and ownership notes here.",
          "- Keep this section focused on this project tree."
        ]
      : [
          "- Add user-level defaults that should apply across multiple Codex workspaces.",
          "- Keep project-specific rules in the project-scoped AGENTS.md instead."
        ];

  return [
    "## Local extension area",
    "",
    ...scopeNotes,
    "- This manual section is preserved across future `agmo setup` runs."
  ].join("\n");
}

function extractLegacyManualBody(content: string, scope: InstallScope): string {
  const heading = "## Local extension area";
  const index = content.indexOf(heading);

  if (index === -1) {
    return defaultManualBody(scope);
  }

  const body = content.slice(index).trim();
  return body || defaultManualBody(scope);
}

export function renderManagedAgentsFile(args: {
  generatedBody: string;
  manualBody: string;
  runtimeBody?: string;
  workerBody?: string;
}): string {
  const sections = [
    MANAGED_MARKER,
    GENERATED_START,
    args.generatedBody.trim(),
    GENERATED_END,
    "",
    RUNTIME_START,
    args.runtimeBody?.trim() ?? "",
    RUNTIME_END,
    "",
    TEAM_WORKER_START,
    args.workerBody?.trim() ?? "",
    TEAM_WORKER_END,
    "",
    MANUAL_START,
    args.manualBody.trim(),
    MANUAL_END
  ];

  return `${sections.join("\n").trimEnd()}\n`;
}

async function readJsonFile<T>(path: string): Promise<T | null> {
  const content = await readTextFileIfExists(path);
  if (!content) {
    return null;
  }

  return JSON.parse(content) as T;
}

async function backupExistingAgentsFile(args: {
  agmoDir: string;
  agentsMdFile: string;
}): Promise<string> {
  const timestamp = new Date().toISOString().replaceAll(":", "-");
  const backupDir = join(args.agmoDir, "backups", "setup", timestamp);
  await mkdir(backupDir, { recursive: true });
  const backupPath = join(backupDir, "AGENTS.md.bak");
  await copyFile(args.agentsMdFile, backupPath);
  return backupPath;
}

async function readRecentActiveSessions(args: {
  sessionsStateDir: string;
  workflowsStateDir: string;
}): Promise<string[]> {
  const now = Date.now();
  const seen = new Set<string>();
  const active = new Set<string>();

  for (const dir of [args.sessionsStateDir, args.workflowsStateDir]) {
    if (!existsSync(dir)) {
      continue;
    }

    for (const entry of await readdir(dir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith(".json")) {
        continue;
      }

      const path = join(dir, entry.name);
      if (seen.has(path)) {
        continue;
      }
      seen.add(path);

      const state = await readJsonFile<SessionStateLike>(path);
      if (!state || state.active !== true) {
        continue;
      }

      const updatedAt =
        typeof state.updated_at === "string" ? Date.parse(state.updated_at) : Number.NaN;
      if (Number.isFinite(updatedAt) && now - updatedAt > ACTIVE_SESSION_WINDOW_MS) {
        continue;
      }

      const sessionId =
        typeof state.session_id === "string" && state.session_id.trim()
          ? state.session_id.trim()
          : entry.name.replace(/\.json$/, "");
      active.add(sessionId);
    }
  }

  return [...active].sort((left, right) => left.localeCompare(right));
}

export async function syncManagedAgentsMd(args: {
  scope: InstallScope;
  force: boolean;
  agentsTemplate: string;
  agentsMdFile: string;
  agmoDir: string;
  sessionsStateDir: string;
  workflowsStateDir: string;
}): Promise<SyncAgentsMdResult> {
  const existing = await readTextFileIfExists(args.agentsMdFile);
  const existingContent = existing ?? "";
  const existingInspection = inspectAgentsContent(existing);
  const runtimeBody = existingInspection.managed
    ? extractSection(existingContent, RUNTIME_START, RUNTIME_END) ?? ""
    : "";
  const workerBody = existingInspection.managed
    ? extractSection(existingContent, TEAM_WORKER_START, TEAM_WORKER_END) ?? ""
    : "";
  const manualBody = existingInspection.managed
    ? extractSection(existingContent, MANUAL_START, MANUAL_END) ?? defaultManualBody(args.scope)
    : existingInspection.legacy_generated
      ? extractLegacyManualBody(existingContent, args.scope)
      : existing
        ? existingContent.trim()
        : defaultManualBody(args.scope);
  const nextContent = renderManagedAgentsFile({
    generatedBody: args.agentsTemplate,
    runtimeBody,
    workerBody,
    manualBody
  });

  const nextFile = {
    managed: true as const,
    runtime_section_present: true,
    team_worker_section_present: true,
    manual_section_present: true
  };

  if (existing === nextContent) {
    return {
      path: args.agentsMdFile,
      status: "unchanged",
      existing_file: existingInspection,
      next_file: nextFile,
      backup: { created: false }
    };
  }

  if (!existing) {
    const result = await writeTextFile(args.agentsMdFile, nextContent);
    return {
      path: result.path,
      status: result.status,
      existing_file: existingInspection,
      next_file: nextFile,
      backup: { created: false }
    };
  }

  if (!existingInspection.managed && !existingInspection.legacy_generated && !args.force) {
    return {
      path: args.agentsMdFile,
      status: "skipped",
      reason: "existing unmanaged AGENTS.md (re-run with --force to adopt it)",
      existing_file: existingInspection,
      next_file: nextFile,
      backup: { created: false },
      guard: {
        skipped_for_unmanaged: true
      }
    };
  }

  const activeSessions =
    args.scope === "project"
      ? await readRecentActiveSessions({
          sessionsStateDir: args.sessionsStateDir,
          workflowsStateDir: args.workflowsStateDir
        })
      : [];

  if (activeSessions.length > 0 && !args.force) {
    return {
      path: args.agentsMdFile,
      status: "skipped",
      reason: "active Agmo session detected for project AGENTS.md",
      existing_file: existingInspection,
      next_file: nextFile,
      backup: { created: false },
      guard: {
        skipped_for_active_session: true,
        active_sessions_detected: activeSessions
      }
    };
  }

  const needsBackup =
    !existingInspection.managed || existingInspection.legacy_generated || args.force;
  const backupPath = needsBackup
    ? await backupExistingAgentsFile({
        agmoDir: args.agmoDir,
        agentsMdFile: args.agentsMdFile
      })
    : undefined;
  const result = await writeTextFile(args.agentsMdFile, nextContent);

  return {
    path: result.path,
    status: result.status,
    existing_file: existingInspection,
    next_file: nextFile,
    forced: args.force || undefined,
    backup: {
      created: Boolean(backupPath),
      ...(backupPath ? { path: backupPath } : {})
    },
    ...(activeSessions.length > 0
      ? {
          guard: {
            active_sessions_detected: activeSessions
          }
        }
      : {})
  };
}

function extractComposableInstructions(content: string): string {
  const inspection = inspectAgentsContent(content);
  if (!inspection.managed) {
    return content.trim();
  }

  const parts = [
    extractSection(content, GENERATED_START, GENERATED_END),
    extractSection(content, MANUAL_START, MANUAL_END)
  ].filter((value): value is string => Boolean(value?.trim()));

  return parts.join("\n\n").trim();
}

function renderOptionalOverlay(start: string, end: string, body?: string): string {
  if (!body?.trim()) {
    return "";
  }

  return [start, body.trim(), end].join("\n");
}

export async function writeSessionComposedAgentsFile(args: {
  cwd?: string;
  sessionId: string;
  runtimeOverlay?: string;
  workerOverlay?: string;
}): Promise<{
  path: string;
  status: WriteStatus;
  sources: {
    user_agents_md?: string;
    project_agents_md?: string;
  };
}> {
  const cwd = args.cwd ?? process.cwd();
  const userAgentsPath = join(codexHomeDir(), "AGENTS.md");
  const projectAgentsPath = join(cwd, "AGENTS.md");
  const sourcePaths = [userAgentsPath, projectAgentsPath];
  const composedParts: string[] = [];
  const seen = new Set<string>();

  for (const path of sourcePaths) {
    if (seen.has(path) || !existsSync(path)) {
      continue;
    }

    seen.add(path);
    const content = await readTextFileIfExists(path);
    if (!content?.trim()) {
      continue;
    }

    const normalized = extractComposableInstructions(content);
    if (!normalized) {
      continue;
    }

    composedParts.push(normalized);
  }

  const runtimeOverlay = renderOptionalOverlay(
    RUNTIME_START,
    RUNTIME_END,
    args.runtimeOverlay
  );
  const workerOverlay = renderOptionalOverlay(
    TEAM_WORKER_START,
    TEAM_WORKER_END,
    args.workerOverlay
  );

  if (runtimeOverlay) {
    composedParts.push(runtimeOverlay);
  }

  if (workerOverlay) {
    composedParts.push(workerOverlay);
  }

  const paths = resolveInstallPaths("project", cwd);
  const sessionDir = join(paths.sessionInstructionsDir, args.sessionId);
  await mkdir(sessionDir, { recursive: true });
  const targetPath = join(sessionDir, "AGENTS.md");
  const result = await writeTextFile(targetPath, `${composedParts.join("\n\n").trim()}\n`);

  return {
    path: result.path,
    status: result.status,
    sources: {
      ...(existsSync(userAgentsPath) ? { user_agents_md: userAgentsPath } : {}),
      ...(existsSync(projectAgentsPath) ? { project_agents_md: projectAgentsPath } : {})
    }
  };
}

export async function removeSessionComposedAgentsFile(args: {
  cwd?: string;
  sessionId: string;
}): Promise<void> {
  const cwd = args.cwd ?? process.cwd();
  const paths = resolveInstallPaths("project", cwd);
  const sessionDir = join(paths.sessionInstructionsDir, args.sessionId);
  await rm(sessionDir, { recursive: true, force: true });
}
